// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwaXBKFrhUOm9YIrc__KxMGRQ-ugh9BIY',
    appId: '1:41688684844:web:b30af933e253a6fa47f489',
    messagingSenderId: '41688684844',
    projectId: 'spinning-quiz',
    authDomain: 'spinning-quiz.firebaseapp.com',
    storageBucket: 'spinning-quiz.appspot.com',
    measurementId: 'G-T9P2SD8EPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbccECoNRVyHtUK7cj-bR203OMdlEXR14',
    appId: '1:41688684844:android:f6705872c6dd209147f489',
    messagingSenderId: '41688684844',
    projectId: 'spinning-quiz',
    storageBucket: 'spinning-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFsJRzDF0diBySI-Cs0Xtfvb4RK-F_f0A',
    appId: '1:41688684844:ios:f7f3b73b8d972e2647f489',
    messagingSenderId: '41688684844',
    projectId: 'spinning-quiz',
    storageBucket: 'spinning-quiz.appspot.com',
    androidClientId: '41688684844-20m4muc1bh5dqmg0b1uf20eisirlf9ik.apps.googleusercontent.com',
    iosClientId: '41688684844-o8cbt88b3cjs14i3ijvt8gc98jfnm9fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFsJRzDF0diBySI-Cs0Xtfvb4RK-F_f0A',
    appId: '1:41688684844:ios:f7f3b73b8d972e2647f489',
    messagingSenderId: '41688684844',
    projectId: 'spinning-quiz',
    storageBucket: 'spinning-quiz.appspot.com',
    androidClientId: '41688684844-20m4muc1bh5dqmg0b1uf20eisirlf9ik.apps.googleusercontent.com',
    iosClientId: '41688684844-o8cbt88b3cjs14i3ijvt8gc98jfnm9fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalYearProject',
  );
}
